from typing import List, Literal
from pydantic import BaseModel, Field

class FinancialState(BaseModel):
    """Represents the current state of the user's financial query and interaction."""
    advice: str               # The advice generated by the agent based on the user's query.


class IntentTag(BaseModel):
    """The detected intent of the user's banking query."""
    category: Literal["greeting", "account_info", "policy_lookup", "investment_advice", "general_faq", "human_handoff", "loan_inquiry", "transaction_help"] = Field(
        description="The category of the banking inquiry."
    )
    confidence: float = Field(description="Confidence score between 0 and 1")

